#define GREEN_BTN_PORT PORTB
#define GREEN_BTN_PIN 6
#define RED_BTN_PORT PORTB
#define RED_BTN_PIN 7

#define DIGIT_ROW_LOW_PORT PORTB
#define DIGIT_ROW_LOW_PIN 0
#define DIGIT_ROW_HIGH_PORT PORTB
#define DIGIT_ROW_HIGH_PIN 1
#define DIGIT_COL_LOW_PORT PORTB
#define DIGIT_COL_LOW_PIN 2
#define DIGIT_COL_HIGH_PORT PORTB
#define DIGIT_COL_HIGH_PIN 3

#define DIGIT_PORT PORTB
#define DIGIT_PIN 5
