#define GREEN_BTN_PORT PORTD
#define GREEN_BTN_PIN 3
#define GREEN_BTN_DDR DDRD
#define RED_BTN_PORT PORTD
#define RED_BTN_PIN 2
#define RED_BTN_DDR DDRD

#define DIGIT_ROW_LOW_PORT PORTB
#define DIGIT_ROW_LOW_PIN 3
#define DIGIT_ROW_LOW_DDR DDRB
#define DIGIT_ROW_HIGH_PORT PORTB
#define DIGIT_ROW_HIGH_PIN 4
#define DIGIT_ROW_HIGH_DDR DDRB
#define DIGIT_COL_LOW_PORT PORTB
#define DIGIT_COL_LOW_PIN 1
#define DIGIT_COL_LOW_DDR DDRB
#define DIGIT_COL_HIGH_PORT PORTB
#define DIGIT_COL_HIGH_PIN 2
#define DIGIT_COL_HIGH_DDR DDRB

#define DIGIT_PORT PORTB
#define DIGIT_PIN 6
#define DIGIT_DDR DDRB

#define DIAL_PORT PORTD
#define DIAL_PIN 5
#define DIAL_DDR DDRD
#define DIAL_IN PIND
#define TICK_PORT PORTD
#define TICK_PIN 4
#define TICK_DDR DDRD
#define TICK_IN PIND
#define HOOK_PORT PORTA
#define HOOK_PIN 1
#define HOOK_DDR DDRA
#define HOOK_IN PINA

#define DEBOUNCE_TIMER_LOOPS 10

#define PRESSTIME 100
