#define GREEN_BTN_PORT PORTB
#define GREEN_BTN_PIN 6
#define GREEN_BTN_DDR DDRB
#define RED_BTN_PORT PORTB
#define RED_BTN_PIN 7
#define RED_BTN_DDR DDRB

#define DIGIT_ROW_LOW_PORT PORTB
#define DIGIT_ROW_LOW_PIN 0
#define DIGIT_ROW_LOW_DDR DDRB
#define DIGIT_ROW_HIGH_PORT PORTB
#define DIGIT_ROW_HIGH_PIN 1
#define DIGIT_ROW_HIGH_DDR DDRB
#define DIGIT_COL_LOW_PORT PORTB
#define DIGIT_COL_LOW_PIN 2
#define DIGIT_COL_LOW_DDR DDRB
#define DIGIT_COL_HIGH_PORT PORTB
#define DIGIT_COL_HIGH_PIN 3
#define DIGIT_COL_HIGH_DDR DDRB

#define DIGIT_PORT PORTB
#define DIGIT_PIN 5
#define DIGIT_DDR DDRB

#define DIAL_PORT PORTD
#define DIAL_PIN 2
#define DIAL_DDR DDRD
#define DIAL_IN PIND
#define TICK_PORT PORTD
#define TICK_PIN 3
#define TICK_DDR DDRD
#define TICK_IN PIND
#define HOOK_PORT PORTD
#define HOOK_PIN 5
#define HOOK_DDR DDRD
#define HOOK_IN PIND

#define DEBOUNCE_TIMER_LOOPS 5
